In [11]:
import gensim
from gensim.models import Word2Vec
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [4]:
# Load the data into a Pandas dataframe
df = pd.read_csv('/content/labelled data (2).csv')

In [5]:
X=df['content']

In [6]:
y=df['label']

In [7]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)


In [8]:
# Build the Word2Vec model
# Assume that 'data' is a list of tokenized documents
# where each document is a list of words
#data = [...] # list of tokenized documents
w2v_model = Word2Vec(X, size=100, window=5, min_count=1, workers=4)


In [9]:
# Vectorize the data using Word2Vec
X_train_w2v = np.array([np.mean([w2v_model.wv[word] for word in document], axis=0) for document in X_train])
X_test_w2v = np.array([np.mean([w2v_model.wv[word] for word in document], axis=0) for document in X_test])

In [12]:
# Train the Gaussian Naive Bayes model
gnb = GaussianNB()
gnb.fit(X_train_w2v, y_train)

GaussianNB()

In [13]:
# Make predictions on the test set
y_pred = gnb.predict(X_test_w2v)

In [14]:
# Evaluate the model
print("Confusion matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification report:")
print(classification_report(y_test, y_pred))
print("Accuracy score:", accuracy_score(y_test, y_pred))

Confusion matrix:
[[17 11  7]
 [34 17  5]
 [45 16 17]]

Classification report:
              precision    recall  f1-score   support

    Negative       0.18      0.49      0.26        35
     Neutral       0.39      0.30      0.34        56
    Positive       0.59      0.22      0.32        78

    accuracy                           0.30       169
   macro avg       0.38      0.34      0.31       169
weighted avg       0.44      0.30      0.31       169

Accuracy score: 0.30177514792899407
